### PR TITLE
Fix ISSUE-1102: Replace the relationship between database and table and data parts from tbl_parts to parts field in Table struct

### LINKED ISSUE #1102: [improvement] replace the relationship between database and table and data parts from tbl_parts to parts field in Table struct
**Summary**

Replace the relationship between database and table and data parts from tbl_parts to parts field in Table struct

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

Replace the relationship between database and table and data parts from tbl_parts to parts field in Table struct

## Changelog

- Improvement

## Related Issues

Fixes #1102

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
@ariesdevil 

If the PR is in WIP, would better to change it to draft :)

**Comment by ariesdevil** [comment]
To accomplish #1102 , I need to change the parts field of the Table structure, and I need to move Database and Table from metatypes to storage_api to circumvent the cyclic dependency. The situation gets more complicated when I finish #1139  based on this PR.

So I'm wondering if this is worth it, and so far I've come up with two options.

1. Leave the definition of the Table's parts field unchanged and still keep the `tbl_parts`, just change the `tbl_parts` in the `StateMachine` from a two-level structure to a one-level one.

2. Give up metatypes and move everything in metatypes to storage_api to avoid dependency issues.

@drmingdrmer @dantengsky I need some suggestions.

**Comment by drmingdrmer** [comment]
> 2\. Give up `metatypes` crate and move everything in `metatypes` to `storage_api` crate to avoid dependency issues.
> 
> I also think that `DataPartInfo` should be part of the meta? If it is, then the current design is misleading because `DataPartInfo` is not handled in the meta_handler, and if it is not, then I should not change the `parts` field in the `Table` from `HashSet<String>` to `HashSet<DataPartInfo>`

`metatypes` is supposed to provide data types that are used by both query and store, AFAIK.
E.g. query depends on `metatypes`, store depends on `metatypes`.

`storage_api`, literally, is a collection of API for query to access store.

Thus to me, the dependency would be:

```
query -> storage_api -> store
  |          |            |
  |          |            |
  |          |            |
  `----------+------------+---> metatypes
```

**Comment by drmingdrmer** [comment]
@ariesdevil 
BTW, later soon the state machine will be converted to a kv store thus all HashMap or BTreeMap will be converted to a individual key-values, e.g. the map for tables will become something like `SledVarTypeTree::as_type<Table>()`.

**Comment by ariesdevil** [comment]
@drmingdrmer So the NO.1 solution is applicable? If so, I'll modify in this way.

**Comment by ariesdevil** [comment]
Or leave these unchanged until we do "covert type to kv" refactoring

**Comment by BohuTANG** [comment]
> Or leave these unchanged until we do "covert type to kv" refactoring

Ok, I've converted this PR status to draft

**Comment by drmingdrmer** [comment]
> @drmingdrmer So the NO.1 solution is applicable? If so, I'll modify in this way.

IMHO this is preferred.

**Comment by drmingdrmer** [comment]
> Or leave these unchanged until we do "covert type to kv" refactoring

Hm... actually I'd love to see small step patches.
Although it introduces more changes but the benefit is that it makes every refactoring step clear and much easier.

**Comment by ariesdevil** [comment]
OK, Every step takes a thousand miles:)

**Comment by drmingdrmer** [comment]
> @ariesdevil
> BTW, later soon the state machine will be converted to a kv store thus all HashMap or BTreeMap will be converted to a individual key-values, e.g. the map for tables will become something like `SledVarTypeTree::as_type<Table>()`.

My point is that a non-nested map reflects the eventual data structure more accurately...

**Pull request closed without merging**
