### PR TITLE
Run rustfmt to get a default format

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

## Summary

`rustfmt` will not trim these commas by default. I think it's better to obey this behavior. Otherwise, many developers with `format-on-save` on will keep being bothered by IDE/Code Editor.

FYI, https://github.com/rust-dev-tools/fmt-rfcs/issues/42#issuecomment-263738648

## Changelog

- Other

## Related Issues

None.

## Test Plan

Unit Tests
Stateless Tests

### CODE REVIEW

**Comment by jyizheng** [comment]
We are using `cargo fmt`. Is its behavior different from `rustfmt`?

**Comment by JmPotato** [comment]
> We are using `cargo fmt`. Is its behavior different from `rustfmt`?

`cargo fmt` is `rustfmt`. They are the same thing. And I have never changed my config before. It's kind of strange we got different format results.

**Comment by JmPotato** [comment]
Oh I know, after switching to the nightly toolchain, the results are the same.

**Comment by jyizheng** [comment]
Good to know. Thanks for your investigation.

**Pull request closed without merging**
