### PR TITLE
TLS http api tests

### LINKED ISSUE #1318: rename to tls_server_cert/key to api_tls_server_cert/key
Ok.
We will change the name to `api_tls_server_cert/key`

_Originally posted by @BohuTANG in https://github.com/datafuselabs/datafuse/issues/1303#issuecomment-894012996_

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

- unit test for TLS HTTP API service (Query)
- rename to `tls_server_cert/key` to `api_tls_server_cert/key`
- move `tests/data/certs` to `tests/certs`
- remove directory `$project_root/tls`
  - using same certs in UT for both https and tls rpc services 
## Changelog

- Improvement

## Related Issues

unit test for #1174
Fixes #1318 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Cool :+1: 
Prefer to remove `tls` root directory to use `tests/data/certs`

**Comment by BohuTANG** [comment]
For the test certs directory, is it better to `tests/certs` instead of `tests/data/certs`?

**Comment by dantengsky** [comment]
> For the test certs directory, is it better to `tests/certs` instead of `tests/data/certs`?

Ok, I will go with `tests/certs`

**Comment by dantengsky** [comment]
> Cool 
> Prefer to remove `tls` root directory to use `tests/data/certs`

Ok

**Review by BohuTANG — APPROVED** [review]
LGTM
Thank you @dantengsky

**Pull request merged**
