### PR TITLE
ISSUE-887 `common/runtime/src/runtime_test.rs` should block until all task quits

### LINKED ISSUE #887: `common/runtime/src/runtime_test.rs` should block until all task quits
**Summary**

```
#[tokio::test(flavor = "multi_thread", worker_threads = 8)]
async fn test_runtime() -> anyhow::Result<()> {
    use crate::*;

    let runtime = Runtime::with_default_worker_threads()?;
    runtime.spawn(async {
        let rt1 = Runtime::with_default_worker_threads().unwrap();
        rt1.spawn(async {
            let rt2 = Runtime::with_worker_threads(1).unwrap();
            rt2.spawn(async {
                let rt3 = Runtime::with_default_worker_threads().unwrap();
                rt3.spawn(async {});
            });
        });
    });
    Ok(())
}
```

### PR DESCRIPTION
**Pull request by dust1**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

use `await` to block until all the async tasks finished.

## Changelog

- Improvement

## Related Issues

Fixes #887

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Cool.
It would be better to use a int variable, add a different number at each runtime spawn and then do a final check of the result.

**Comment by ariesdevil** [comment]
> Cool.
> It would be better to use an int variable, add a different number at each runtime spawn and then do a final check of the result.

I think using something like [waitgroup](https://docs.rs/waitgroup/0.1.2/waitgroup/) could be a more elegant solution.

**Comment by BohuTANG** [comment]
Need to do 'make lint' locally and push again :)

**Comment by dust1** [comment]
> Need to do 'make lint' locally and push again :)

Sorry, I plan to fix it later in the evening.

**Comment by BohuTANG** [comment]
> > Cool.
> > It would be better to use an int variable, add a different number at each runtime spawn and then do a final check of the result.
> 
> I think using something like [waitgroup](https://docs.rs/waitgroup/0.1.2/waitgroup/) could be a more elegant solution.

It's OK here, since this is a test improvement.

**Comment by BohuTANG** [comment]
> > Need to do 'make lint' locally and push again :)
> 
> Sorry, I plan to fix it later in the evening.

I have fixed it in this commit: https://github.com/datafuselabs/datafuse/pull/1201/commits/eb1be55c22e63cd4e3cfc78e760935c6dcaed889

**Review by BohuTANG — APPROVED** [review]
LGTM
Thank you @dust1

**Comment by dust1** [comment]
> LGTM
> Thank you @dust1

Thanks, I will try my best to participate in datafuse. :)

**Pull request merged**
