### PR TITLE
[refactor/test] imporve http api

### PR DESCRIPTION
**Pull request by PsiACE**
Signed-off-by: Chojan Shang <psiace@outlook.com>

I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

- [x] [refactor] query http api hello -> health
- [x] store health check http api
- [x] ~more test for store‘s api~ add test for tls http service

## Changelog

- Improvement
- Build/Testing/CI

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
It looks the router change to 'ping' is simple

**Comment by PsiACE** [comment]
> It looks the router change to 'ping' is simple

I prefer `health`, and if possible, some component detection could be added here.

**Comment by sundy-li** [comment]
> > It looks the router change to 'ping' is simple
> 
> I prefer `health`, and if possible, some component detection could be added here.

+1,  https://microservices.io/patterns/observability/health-check-api.html

**Comment by BohuTANG** [comment]
> > It looks the router change to 'ping' is simple
> 
> I prefer `health`, and if possible, some component detection could be added here.

It's ok here 👍

**Review by ZhiHanZ — APPROVED** [review]
LGTM

**Pull request merged**
