### PR TITLE
fix select string with the same name as the column return wrong result

### LINKED ISSUE #1509: [BUG] string with the same name is parsed into column
**Summary**

**How to reproduce**
```
mysql> create table t(id int,b int) Engine=Memory;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t values(1,2),(3,4);
Query OK, 0 rows affected (0.01 sec)

mysql> select id,'id' from t;
+------+------+
| id   | id   |
+------+------+
|    1 |    1 |
|    3 |    3 |
+------+------+
2 rows in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

```
mysql> create table t(id int,b int) Engine=Memory;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t values(1,2),(3,4);
Query OK, 0 rows affected (0.01 sec)

mysql> select id,'id' from t;
+------+------+
| id   | 'id' |
+------+------+
|    1 |   id |
|    3 |   id |
+------+------+
2 rows in set (0.00 sec)

mysql> explain SELECT number, 'number', "number" FROM numbers(3) AS a order by a.number;
+----------------------------------------------------------------------------------------------------------------------+
| explain                                                                                                              |
+----------------------------------------------------------------------------------------------------------------------+
| Projection: number:UInt64, number:Utf8, number:UInt64                                                                |
|   Sort: number:UInt64                                                                                                |
|     Expression: number:UInt64, number:Utf8 (Before OrderBy)                                                          |
|       ReadDataSource: scan partitions: [1], scan schema: [number:UInt64], statistics: [read_rows: 3, read_bytes: 24] |
+----------------------------------------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)
```

## Changelog

- Bug Fix

## Related Issues

Fixes #1509 

## Test Plan

Stateless Tests

### CODE REVIEW

**Review by zhang2014 — APPROVED** [review]
LGTM @zhyass Thank you.

**Comment by zhyass** [comment]
failures:
1341
    optimizers::optimizer_constant_folding_test::tests::test_constant_folding_optimizer
1342
    optimizers::optimizer_statistics_exact_test::tests::test_statistics_exact_optimizer
1343
    sql::plan_parser_test::test_plan_parser

**Comment by BohuTANG** [comment]
> failures:
> optimizers::optimizer_constant_folding_test::tests::test_constant_folding_optimizer
> optimizers::optimizer_statistics_exact_test::tests::test_statistics_exact_optimizer
> sql::plan_parser_test::test_plan_parser

I guess this patch broken them.

**Comment by zhyass** [comment]
> > failures:
> > optimizers::optimizer_constant_folding_test::tests::test_constant_folding_optimizer
> > optimizers::optimizer_statistics_exact_test::tests::test_statistics_exact_optimizer
> > sql::plan_parser_test::test_plan_parser
> 
> I guess this patch broken them.

Yes, I have get the cause and try to resolved.

**Comment by BohuTANG** [comment]
Or we should change the tests:
```
---- sql::plan_parser_test::test_plan_parser stdout ----
thread 'sql::plan_parser_test::test_plan_parser' panicked at 'assertion failed: `(left == right)`: cast-passed

Diff < left / right > :
<"Projection: cast(1 as Int32):Int32\n  Expression: cast(1 as Int32):Int32 (Before Projection)\n    ReadDataSource: scan partitions: [1], scan schema: [dummy:UInt8], statistics: [read_rows: 1, read_bytes: 1]"
>"Projection: cast('1' as Int32):Int32\n  Expression: cast(1 as Int32):Int32 (Before Projection)\n    ReadDataSource: scan partitions: [1], scan schema: [dummy:UInt8], statistics: [read_rows: 1, read_bytes: 1]"

```

**Comment by zhyass** [comment]
> Or we should change the tests:
> 
> ```
> ---- sql::plan_parser_test::test_plan_parser stdout ----
> thread 'sql::plan_parser_test::test_plan_parser' panicked at 'assertion failed: `(left == right)`: cast-passed
> 
> Diff < left / right > :
> <"Projection: cast(1 as Int32):Int32\n  Expression: cast(1 as Int32):Int32 (Before Projection)\n    ReadDataSource: scan partitions: [1], scan schema: [dummy:UInt8], statistics: [read_rows: 1, read_bytes: 1]"
> >"Projection: cast('1' as Int32):Int32\n  Expression: cast(1 as Int32):Int32 (Before Projection)\n    ReadDataSource: scan partitions: [1], scan schema: [dummy:UInt8], statistics: [read_rows: 1, read_bytes: 1]"
> ```



> Or we should change the tests:
> 
> ```
> ---- sql::plan_parser_test::test_plan_parser stdout ----
> thread 'sql::plan_parser_test::test_plan_parser' panicked at 'assertion failed: `(left == right)`: cast-passed
> 
> Diff < left / right > :
> <"Projection: cast(1 as Int32):Int32\n  Expression: cast(1 as Int32):Int32 (Before Projection)\n    ReadDataSource: scan partitions: [1], scan schema: [dummy:UInt8], statistics: [read_rows: 1, read_bytes: 1]"
> >"Projection: cast('1' as Int32):Int32\n  Expression: cast(1 as Int32):Int32 (Before Projection)\n    ReadDataSource: scan partitions: [1], scan schema: [dummy:UInt8], statistics: [read_rows: 1, read_bytes: 1]"
> ```

fixed

**Pull request merged**
