### PR TITLE
[ci] add basic build cache

### LINKED ISSUE #913: [ci] add cache for build
**Summary**

looks like:

```
      - name: Cache cargo registry
        if: ${{ ! matrix.rust-free }}
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ env.CACHE_RESET_KEY }}-${{ runner.os }}-${{ matrix.rust }}-cargo-${{ matrix.make.name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ env.CACHE_RESET_KEY }}-${{ runner.os }}-${{ matrix.rust }}-cargo-${{ matrix.make.name }}-
            ${{ env.CACHE_RESET_KEY }}-${{ runner.os }}-${{ matrix.rust }}-cargo-
      - name: Save sccache
        if: ${{ ! matrix.rust-free }}
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: ${{ env.CACHE_RESET_KEY }}-${{ runner.os }}-${{ matrix.rust }}-sccache-${{ matrix.make.name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ env.CACHE_RESET_KEY }}-${{ runner.os }}-${{ matrix.rust }}-sccache-${{ matrix.make.name }}-
            ${{ env.CACHE_RESET_KEY }}-${{ runner.os }}-${{ matrix.rust }}-sccache-
```

### PR DESCRIPTION
**Pull request by PsiACE**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

add basic build cache

need to add secrets.CACHE_RESET_KEY to control the cache version.

for example, clippy time is reduced from `5m 48s` to `25.74s`. 

## Changelog

- Build/Testing/CI

## Related Issues

Fixes #913 

## Test Plan

No

### CODE REVIEW

**Comment by BohuTANG** [comment]
This improve is awesome :+1:

**Comment by BohuTANG** [comment]
Hi @PsiACE ,
How to config `CACHE_RESET_KEY` and when we need to upgrade the version?

**Comment by PsiACE** [comment]
> How to config `CACHE_RESET_KEY` 

set: https://github.com/datafuselabs/datafuse/settings/secrets/actions/new

> and when we need to upgrade the version?

When we want to forcibly refresh the cache, such as cache failure

**Comment by PsiACE** [comment]
Don’t merge for now

**Comment by BohuTANG** [comment]
Thank you @PsiACE 
I have add `CACHE_RESET_KEY` key for it.

**Comment by BohuTANG** [comment]
> Don’t merge for now

Ok, maybe you can convert it to draft next tie, no one can merge it until it's ready for review again.

**Comment by drmingdrmer** [comment]
Great!

**Comment by dantengsky** [comment]
> for example, clippy time is reduced from 5m 48s to 25.74s.

Love it

**Review by BohuTANG — APPROVED** [review]
Look great to me
Thank you @PsiACE

**Pull request merged**
