### PR TITLE
ISSUE-204 support kill query or connection statement

### LINKED ISSUE #204: Support cancel for the stream executing
**Summary**

Support cancel when the pipeline stream executing.

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

Support kill query|connection statement

## Changelog

- New Feature

## Related Issues

Fixes #204

### CODE REVIEW

**Comment by BohuTANG** [comment]
Oops, there are conflicts with master.
cc @zhang2014

**Comment by zhang2014** [comment]
> Oops, there are conflicts with master.
> cc @zhang2014

Sorry, I forgot to change it to daft : (

**Review by sundy-li — APPROVED** [review]
LGTM

**Comment by sundy-li** [comment]
BTW, will we support batch kill queries ?

Like: 
```
kill query where user = 'default';
kill query where sql like 'xxx';
```

**Comment by zhang2014** [comment]
> BTW, will we support batch kill queries ?

This is ClickHouse style, let's implement it in other pr.

**Pull request merged**
