### PR TITLE
Logical types

### LINKED ISSUE #1627: Introduce custom logic types on arrow2
**Summary**

tasks:
- [ ] Custom logic types on arrow2 using `ARROW::extension::name` in field's metadata,  [extension types](https://arrow.apache.org/docs/python/extending_types.html#defining-extension-types-user-defined-types)
- [ ] `DataArray` will be related only with physical types, so `DateTime32` and `UInt32` will share same physical array inside.
- [ ] Refactor `DataArray<T>`

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

tasks:
- [x] Custom logic types on arrow2 using `ARROW::extension::name` in field's metadata,  [extension types](https://arrow.apache.org/docs/python/extending_types.html#defining-extension-types-user-defined-types)
- [x] `DataArray`/`DataValue` will be related only with physical types, so `DateTime32` and `UInt32` will share same physical array inside.
- [x] Refactor `DataArray<T>`
- [x] Support `Date16`, `Date32`, `DateTime32` types
- [x] Add `now()`, `today()` functions

Summary about this PR

## Changelog

- Improvement
 

## Related Issues

Fixes #1627

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
Works now:

```
mysql> select toDateTime(number ) as c  from numbers(3) order by c;
+---------------------+
| c                   |
+---------------------+
| 1970-01-01 00:00:00 |
| 1970-01-01 00:00:01 |
| 1970-01-01 00:00:02 |
+---------------------+
3 rows in set (0.02 sec)

mysql> select toDate(number ) as c  from numbers(3) order by c;
+------------+
| c          |
+------------+
| 1970-01-01 |
| 1970-01-02 |
| 1970-01-03 |
+------------+
3 rows in set (0.01 sec)
```

**Comment by sundy-li** [comment]
The cached building is broken

**Comment by BohuTANG** [comment]
> The cached building is broken

I have updated the cache key.

**Comment by BohuTANG** [comment]
> > The cached building is broken
> 
> I have updated the cache key.

Still not working, @PsiACE  may help :)

**Comment by PsiACE** [comment]
> Still not working, @PsiACE may help :)

set `CARGO_INCREMENTAL: '0'` for workflows

**Comment by BohuTANG** [comment]
> > Still not working, @PsiACE may help :)
> 
> set `CARGO_INCREMENTAL: '0'` for workflows
> 
> fyi,
> 
> https://github.com/datafuselabs/datafuse/blob/238074515b158f00e58444771baf63f1160a2031/.github/workflows/unit-tests.yml#L48

In this barnch, it's already `CARGO_INCREMENTAL: '0'`, please see:
https://github.com/datafuselabs/datafuse/blob/238074515b158f00e58444771baf63f1160a2031/.github/workflows/unit-tests.yml#L48

**Comment by BohuTANG** [comment]
@PsiACE 
Found a build log:
```
Cache restored successfully
Cache restored from key: Linux-cargo-buildcache--939e19488e3de5d8898a4c80eb4c56293237222f3dbe16428133ed00aa480d15
```

Not sure how to clean the cache.

**Review by zhang2014 — APPROVED** [review]
LGTM

**Pull request merged**
