### PR TITLE
Improve GroupBy 

### LINKED ISSUE #1340: Build for Debug Error
Error 
Running `cargo build --bin=fuse-query --package=fuse-query --message-format=json`...
   Compiling common-flights v0.1.0 (/Users/wangzhen/RustProject/datafuse/common/flights)
error[E0432]: unresolved import `tonic::transport::ClientTlsConfig`
  --> common/flights/src/dns_resolver.rs:25:5
   |
25 | use tonic::transport::ClientTlsConfig;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ClientTlsConfig` in `transport`

error[E0282]: type annotations needed
   --> common/flights/src/dns_resolver.rs:151:45
    |
151 |                     let client_tls_config = Self::client_tls_config(&conf).await.map_err(|e| {
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
    |
    = note: type must be known at this point

error[E0599]: no method named `tls_config` found for struct `Endpoint` in the current scope
   --> common/flights/src/dns_resolver.rs:157:29
    |
157 |                     builder.tls_config(client_tls_config).map_err(|e| {
    |                             ^^^^^^^^^^ method not found in `Endpoint`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0282, E0432, E0599.

For more information about an error, try `rustc --explain E0282`.

error: could not compile `common-flights` due to 4 previous errors

**Operating system**
Mac

OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**rust version**
```text
$ rustc --version
rustc 1.56.0-nightly (e3b1c12be 2021-08-02)
$ cargo --version
cargo 1.55.0-nightly (d21c22870 2021-07-26)
```

**Datafuse git version**

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

- More generic way in AggregateFunction.
- Refactor group by, disable take block in the group by, this can avoid lots memcpy, performance can improve 30%~50%.
- Now we don't need to store "_group_keys" in the partial group by stage, using deserialize from hash key instead.
- Improve Cast performance in arrow2.
- Always convert constant column to full column before aggregation.
-  ...
## Changelog

- Improvement

## Related Issues

Fixes #1340  #644 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
GroupBy is 1.7X faster.

https://test-1306375239.cos.accelerate.myqcloud.com/report/1334/b7b370b3e8336ae007a1fa143939675443c9b2f0/36b91cc0-5a19-4256-9644-6c71011831a4/performance.html

**Comment by sundy-li** [comment]
https://test-1306375239.cos.accelerate.myqcloud.com/report/1334/0a0009ee85293be40899e94a553f9874f3b8265f/3471f870-3f4c-4562-b845-ccaef75733ea/performance.html

GroupBy is nearly 2.0X faster now!

**Review by BohuTANG — APPROVED** [review]
LGTM
Thank you @sundy-li

**Pull request merged**
