### PR TITLE
ISSUE 1228: Use batch mode to speed up tracing data sending

### PR DESCRIPTION
**Pull request by SGZW**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

solve #1228
use batch mode to speed up tracing data sending

## Changelog

- Improvement

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by drmingdrmer** [comment]
@SGZW Thanks man! 

Since the distributed tracing has no corresponding test yet, one need manually check the data is sent as well with:
```
docker run -d -p6831:6831/udp -p6832:6832/udp -p16686:16686 jaegertracing/all-in-one:latest
FUSE_JAEGER=on RUST_LOG=trace cargo test
# open http://localhost:16686/ in a browser
```

Mind giving a comment to let people know that this is manually tested?

**Comment by SGZW** [comment]
> @SGZW Thanks man!
> 
> Since the distributed tracing has no corresponding test yet, one need manually check the data is sent as well with:
> 
> ```
> docker run -d -p6831:6831/udp -p6832:6832/udp -p16686:16686 jaegertracing/all-in-one:latest
> FUSE_JAEGER=on RUST_LOG=trace cargo test
> # open http://localhost:16686/ in a browser
> ```
> 
> Mind giving a comment to let people know that this is manually tested?

ok, i will display the test image

**Comment by SGZW** [comment]
image
can be reproduced by follow command:
FUSE_JAEGER=on RUST_LOG=trace OTEL_BSP_SCHEDULE_DELAY=1 cargo test -p fuse-store --lib

OTEL_BSP_SCHEDULE_DELAY is a env variable to set batch exporter worker sleep interval

**Comment by drmingdrmer** [comment]
> OTEL_BSP_SCHEDULE_DELAY is a env variable to set batch exporter worker sleep interval

Thanks. It's great!

**Review by drmingdrmer — APPROVED** [review]

**Pull request merged**
