### PR TITLE
[fuzz test] add simple hfuzz for parse_sql

### LINKED ISSUE #326: Add fuzz for sql parser
**Summary**

Use [honggfuzz](https://github.com/rust-fuzz/honggfuzz-rs#dependencies)

```
use honggfuzz::fuzz;

fn main() {
    loop {
        fuzz!(|data: String| {
            let _ = your_method(&data);
        });
    }
}
```

### PR DESCRIPTION
**Pull request by PsiACE**
## Summary

Try to add fuzz test for `parse_sql`, but the terminal will directly crash, failing to complete the fuzz test. 

Need some review and investigation.

## Changelog

- Build/Testing/CI

## Related Issues

Fixes #326 

## Test Plan

Just fuzz test, `cargo hfuzz run fuzz_parse_sql`.

Signed-off-by: Chojan Shang <psiace@outlook.com>

### CODE REVIEW

**Comment by PsiACE** [comment]
@BohuTANG sqlparser can perform fuzz testing through hfuzz, but currently fusequery cannot complete this test temporarily.

**Comment by BohuTANG** [comment]
> @BohuTANG sqlparser can perform fuzz testing through hfuzz, but currently fusequery cannot complete this test temporarily.

Cool, we can make the test work in another patch.
Really nice work!

**Review by BohuTANG — APPROVED** [review]
LGTM

**Comment by PsiACE** [comment]
It is worth mentioning that the fuzz test results of sqlparser are not ideal, and there will be more crashes.

**Comment by BohuTANG** [comment]
> It is worth mentioning that the fuzz test results of sqlparser are not ideal, and there will be more crashes.

Reasonable, we need more work on the sqlparser later.

**Pull request merged**
