### PR TITLE
Support the aggregation functions argMax and argMin

### LINKED ISSUE #466: Support argMax/argMin
**Summary**
pretty useful aggregate function

**Example**

Input table:

``` text
┌─user─────┬─salary─┐
│ director │   5000 │
│ manager  │   3000 │
│ worker   │   1000 │
└──────────┴────────┘
```

Query:

``` sql
SELECT argMax(user, salary) FROM salary;
```

Result:

``` text
┌─argMax(user, salary)─┐
│ director             │
└──────────────────────┘
```

Query:

``` sql
SELECT argMin(user, salary) FROM salary;
```

Result:

``` text
┌─argMax(user, salary)─┐
│ worker               │
└──────────────────────┘
```

[argMax](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/argmax/)
[argMin](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/argmin/)

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

## Summary

* Support the aggregation functions `argMax` and `argMin`.
* Add test cases.

## Changelog

- New Feature

## Related Issues

Close #466.

## Test Plan

Unit Tests
Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
To add a stateless test is better, refer:  `./scripts/ci/ci-stateless-tests-standalone.sh`

**Comment by JmPotato** [comment]
> To add a stateless test is better, refer: `./scripts/ci/ci-stateless-tests-standalone.sh`

When I try to add a statement like:

```sql
SELECT argMax(a, b) from (select number as a, number as b from numbers_mt(10000) JOIN numbers_mt(10000));
```

Then an error occurs:

```shell
ERROR 1105 (HY000) at line 7: Code: 8, displayText = Unsupported function: "argMax".
```

I think these lines should be ok to register the two new functions, what do I miss?

```rust
impl AggregatorFunction {
    pub fn register(map: FactoryFuncRef) -> Result<()> {
        let mut map = map.write();
        map.insert("count", AggregateCountFunction::try_create);
        map.insert("min", AggregateMinFunction::try_create);
        map.insert("max", AggregateMaxFunction::try_create);
        map.insert("sum", AggregateSumFunction::try_create);
        map.insert("avg", AggregateAvgFunction::try_create);
        map.insert("argMin", AggregateArgMinFunction::try_create);
        map.insert("argMax", AggregateArgMaxFunction::try_create);
        Ok(())
    }
}
```

**Comment by zhang2014** [comment]
FuseQuery always uses lowercase function names to get functions.

reference :
https://github.com/datafuselabs/datafuse/blob/master/common/functions/src/function_factory.rs#L40

**Comment by JmPotato** [comment]
> FuseQuery always uses lowercase function names to get functions.
> 
> 
> 
> reference :
> 
> https://github.com/datafuselabs/datafuse/blob/master/common/functions/src/function_factory.rs#L40

Oops, thanks for pointing out!

**Review by sundy-li — APPROVED** [review]
LGTM, thanks for the contribution.

**Pull request merged**
