### PR TITLE
Add `yesterday`, `tomorrow` date functions

### LINKED ISSUE #853: [functions] Functions Working with Date/DateTime
From  https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/

prio order from high to low
- [x] now (#1648)
- [x] today (#1648)
- [x] yesterday (#1673)
- [x] tomorrow (#1673)
- [x] toDate, toDateTime    (cast number/string into Date/DateTime)  
- [x] timeSlot (#1715)
- [x] toYYYYMM (#1726)
- [x] toYYYYMMDD (#1767)
- [x] toYYYYMMDDhhmmss (#1767)
- [x] toStartOfYear (#1826)
- [x] toStartOfISOYear (#1826)
- [x] toStartOfQuarter #1848
- [x] toStartOfMonth  #1848
- [x] toStartOfWeek (#1942) 
- [x] toStartOfDay (#1715)
- [x] toStartOfHour (#1715)
- [x] toStartOfMinute (#1715)
- [x] toStartOfSecond (#1715)
- [x] toStartOfFiveMinute (#1715)
- [x] toStartOfTenMinutes (#1715)
- [x] toStartOfFifteenMinutes  (#1715)
- [x] toMonth (#2042)
- [x] toDayOfYear (#2050)
- [x] toDayOfMonth (#2050)
- [x] toDayOfWeek (#2050)
- [x] toHour (#2309)
- [x] toMinute (#2309)
- [x] toSecond (#2309)
- [x] toMonday (#2317)

Low priority:
- timeZone
- toTimeZone
- timeZoneOf
- timeZoneOffset
- toStartOfInterval
- toYear
- toQuarter
- toUnixTimestamp
- toTime
- toRelativeYearNum
- toRelativeQuarterNum
- toRelativeMonthNum
- toRelativeWeekNum
- toRelativeDayNum
- toRelativeHourNum
- toRelativeMinuteNum
- toRelativeSecondNum
- toISOYear
- toISOWeek
- toWeek
- toYearWeek
- date_trunc
- date_add
- date_diff
- date_sub
- timestamp_add
- timestamp_sub
- addYears
- subtractYears
- timeSlots
- formatDateTime
- dateName
- FROM_UNIXTIME
- toModifiedJulianDay
- toModifiedJulianDayOrNull
- fromModifiedJulianDay
- fromModifiedJulianDayOrNull

### PR DESCRIPTION
**Pull request by dust1**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

Maybe I need a test case ?

## Changelog

- New Feature

## Related Issues

Fixes #853

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
@dust1 

It's more better if we add some unit-test and stateless for the yesterday function.
Thank you.

**Comment by sundy-li** [comment]
Try to add stateless tests of   

```
select  today() - 1 = yesterday();
select   today() - yesterday()  = 1;
select  today()
```

**Comment by dust1** [comment]
> Try to add stateless tests of
Yes I do, but like yesterday I say, when i execute `make stateless-test`, the datafuse-test was error. #1676. 
can i use the github workflow to check?

**Comment by dust1** [comment]
> Try to add stateless tests of


Try to add stateless tests of
Yes I do, but like yesterday I say, when i execute make stateless-test, the datafuse-test was error. #1676.
can i use the github workflow to check?

**Comment by BohuTANG** [comment]
> > Try to add stateless tests of
> 
> Try to add stateless tests of
> Yes I do, but like yesterday I say, when i execute make stateless-test, the datafuse-test was error. #1676.
> can i use the github workflow to check?

Sure :)

**Comment by dust1** [comment]
> 1. Can we merge yesterday() and today() into one single function using impl dispatch?


I try. : )

**Comment by dust1** [comment]
>  Can we merge yesterday() and today() into one single function using impl dispatch?


hello? I have some problems. 
how can i implement `impl DateFunction for Today {}`? 
and then how can i register in
```
pub fn register(map: FactoryFuncRef) -> Result<()> {
        let mut map = map.write();
        map.insert("today".into(), TodayFunction::try_create);
        ...
        Ok(())
    }
```
Sorry I don’t know how to use "dispatch" in practice for the time being : (

**Comment by sundy-li** [comment]
@dust1  I've added this, you can have a look and add tests for these three functions.

**Comment by dust1** [comment]
> @dust1 I've added this, you can have a look and add tests for these three functions.

thanks ：）

**Review by sundy-li — APPROVED** [review]
LGTM, thanks @dust1

**Pull request merged**
