### PR TITLE
Add Support SHOW TABLES FROM statament

### LINKED ISSUE #1387: Support SHOW TABLES FROM statament
**Summary**

https://www.db-fiddle.com/f/iLtiAbwXGB92HNENybo1T3/0
```
CREATE DATABASE ss;
CREATE TABLE `ss`.`table_1`(id varchar(200));
SHOW TABLES FROM `ss`;
SHOW TABLES IN `ss`;
```

### PR DESCRIPTION
**Pull request by dust1**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

Summary about this PR

## Changelog

- New Feature

## Related Issues

Fixes #1387

## Test Plan

Unit Tests  ok

Stateless Tests. ok

### CODE REVIEW

**Comment by dust1** [comment]
Support SHOW TABLES FROM statament.
It's been a long time....

**Comment by sundy-li** [comment]
Nice work, another issue can be addressed in this pr.

clickhouse handler
```
datafuse :) show tables;

SHOW TABLES

Query id: 722a09b9-2b2e-4d32-862c-efeb0a34b209


Received exception from server (version 2021.5.0):
Code: 1002. DB::Exception: Received from pc:9000. DB:Exception. sql parser error: Expected like or where, found: ;.

0 rows in set. Elapsed: 0.019 sec.

datafuse :) show tables

SHOW TABLES

Query id: c47de57a-093e-4d70-8339-418aa9ae93ff

Ok.

0 rows in set. Elapsed: 0.030 sec.
```

**Comment by dust1** [comment]
> Nice work, another issue can be addressed in this pr.
> 
> clickhouse handler
> 
> ```
> datafuse :) show tables;
> 
> SHOW TABLES
> 
> Query id: 722a09b9-2b2e-4d32-862c-efeb0a34b209
> 
> 
> Received exception from server (version 2021.5.0):
> Code: 1002. DB::Exception: Received from pc:9000. DB:Exception. sql parser error: Expected like or where, found: ;.
> 
> 0 rows in set. Elapsed: 0.019 sec.
> 
> datafuse :) show tables
> 
> SHOW TABLES
> 
> Query id: c47de57a-093e-4d70-8339-418aa9ae93ff
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.030 sec.
> ```

ok

**Comment by dust1** [comment]
> Nice work, another issue can be addressed in this pr.
> 
> clickhouse handler
> 
> ```
> datafuse :) show tables;
> 
> SHOW TABLES
> 
> Query id: 722a09b9-2b2e-4d32-862c-efeb0a34b209
> 
> 
> Received exception from server (version 2021.5.0):
> Code: 1002. DB::Exception: Received from pc:9000. DB:Exception. sql parser error: Expected like or where, found: ;.
> 
> 0 rows in set. Elapsed: 0.019 sec.
> 
> datafuse :) show tables
> 
> SHOW TABLES
> 
> Query id: c47de57a-093e-4d70-8339-418aa9ae93ff
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.030 sec.
> ```

ok

**Comment by dust1** [comment]
> Nice work, another issue can be addressed in this pr.
> 
> clickhouse handler
> 
> ```
> datafuse :) show tables;
> 
> SHOW TABLES
> 
> Query id: 722a09b9-2b2e-4d32-862c-efeb0a34b209
> 
> 
> Received exception from server (version 2021.5.0):
> Code: 1002. DB::Exception: Received from pc:9000. DB:Exception. sql parser error: Expected like or where, found: ;.
> 
> 0 rows in set. Elapsed: 0.019 sec.
> 
> datafuse :) show tables
> 
> SHOW TABLES
> 
> Query id: c47de57a-093e-4d70-8339-418aa9ae93ff
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.030 sec.
> ```

should be ignored ';'?

**Comment by dust1** [comment]
> Nice work, another issue can be addressed in this pr.
> 
> clickhouse handler
> 
> ```
> datafuse :) show tables;
> 
> SHOW TABLES
> 
> Query id: 722a09b9-2b2e-4d32-862c-efeb0a34b209
> 
> 
> Received exception from server (version 2021.5.0):
> Code: 1002. DB::Exception: Received from pc:9000. DB:Exception. sql parser error: Expected like or where, found: ;.
> 
> 0 rows in set. Elapsed: 0.019 sec.
> 
> datafuse :) show tables
> 
> SHOW TABLES
> 
> Query id: c47de57a-093e-4d70-8339-418aa9ae93ff
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.030 sec.
> ```

Hello. I fix `show tables;` statament. Can you review it

**Comment by dust1** [comment]
@sundy-li

**Comment by BohuTANG** [comment]
@dust1 
Hi!
A tip:
if the PR is ready for review, please click `Ready for review`(convert the PR from draft to ready), and then some one will review on it.

**Review by sundy-li — APPROVED** [review]
LGTM

**Pull request merged**
