### PR TITLE
error on cte because it is nyi

### LINKED ISSUE #27: CTE is not supported, but fuse reports internal("Unknown database: \'default\'")
mysql> with t as ( select sum(number)n from system.numbers_mt(1000))select * from t;
ERROR 1105 (HY000): Internal("Unknown database: \'default\'")

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

## Summary

Return proper error if query contains CTE. We are planning to do on #514 .

## Changelog

- Not for changelog

## Related Issues

Fixes #27 

## Test Plan

Manually verify the output. I'd glad to know where to add tests.

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @BohuTANG @l1t1

**Comment by BohuTANG** [comment]
Thanks for the contribution :100: 

It would be better to add a CTE error check case in `plan_parser_test`:
https://github.com/datafuselabs/datafuse/blob/4989b459d64006888c6731c6686cf35e9a848eda/fusequery/query/src/sql/plan_parser_test.rs#L10

**Comment by tisonkun** [comment]
> Thanks for the contribution 💯
> 
> It would be better to add a CTE error check case in `plan_parser_test`:
> https://github.com/datafuselabs/datafuse/blob/4989b459d64006888c6731c6686cf35e9a848eda/fusequery/query/src/sql/plan_parser_test.rs#L10

Thanks! Updated.

**Review by BohuTANG — APPROVED** [review]
LGTM

**Pull request merged**
