### PR TITLE
[compute] use auto vectorized compute for some cases

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

-   Use auto vectorized compute for `sum and rem`, this can avoid type casting from other types.
-  `get` instead `get_mut`
-   Custom Hash functions

## Changelog

- Performance Improvement

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by ZhiHanZ** [comment]
please merge latest master patch for perf tests

**Comment by sundy-li** [comment]
> please merge latest master patch for perf tests

Already merged, still failure encount.

**Comment by ZhiHanZ** [comment]
> > please merge latest master patch for perf tests
> 
> Already merged, still failure encount.

performance dispatch file is outdated, https://github.com/datafuselabs/datafuse/runs/3290701187?check_suite_focus=true

**Review by zhang2014 — APPROVED** [review]
Perfect

**Pull request merged**
