### PR TITLE
[store] feature: MetaNode suuport AddDatabase

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

##### [store] feature: MetaNode suuport AddDatabase
According to the latest design, databases and tables are now a part of
meta data, no longer a DFS file.

- Add two seq number fields for generating globally unique database id
  and table id.
  E.g. a database may have the same id with a table.
  But two databases or tables will never have the same id.

  When adding database or table, the unique seq is generated by raft
  state machine, when the AddDatabase log applies.

- Define Database and Table with serde.

- Add two BTreeMap to Meta to store databases and tables.

- If the database with the name to add present, nothing is done.

- Reading database is done by reading from the local raft state machine.
  Thus there is chance the last added database can not be seen on other
  ndoe.

  But the node that submit the AddDatabase request can always get the
  result from raft response.

TODO: ActionHandler should adopt this change by saving database into
raft cluster instead of into local in-memory data.

Fixes: #871

## Changelog

- New Feature

- Improvement

## Related Issues

#271

### CODE REVIEW

**Comment by drmingdrmer** [comment]
@dantengsky May these APIs be what you want for accessing raft meta data? 🤔 Anything else you want, let me know.

**Comment by dantengsky** [comment]
Thanks, Bro! Looks nice to me。

We may need to share/extract some common data structures to `common-xxx`, but let's figure out that latter.

BTW, quick move & salute!

**Review by dantengsky — APPROVED** [review]
let's roll

**Comment by drmingdrmer** [comment]
> Thanks, Bro! Looks nice to me。
> 
> We may need to share/extract some common data structures to `common-xxx`, but let's figure out that latter.
> 
> BTW, quick move & salute!

Aye sir!

**Pull request merged**
