### PR TITLE
Add optimize histogram metric

### PR DESCRIPTION
**Pull request by jyz0309**
Signed-off-by: Alkaid <alkaid@AlkaiddeMacBook-Pro.local>

I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

Add a histogram metric for optimizer. We can use this metric to know the P99,P90....e.t.c used time by optimizer.

## Changelog

- Other 

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by jyz0309** [comment]
@BohuTANG PTAL

**Comment by jyz0309** [comment]
BTW, I think we can add this type of metric in every module. Just like `executor`,`parser`.

**Review by BohuTANG — APPROVED** [review]
Thank you @jyz0309

**Comment by BohuTANG** [comment]
> BTW, I think we can add this type of metric in every module. Just like `executor`,`parser`.

Right, that's what we did

**Pull request merged**
