### PR TITLE
ISSUE-1191: fix mysql client borderline missing for EXPLAIN statement

### LINKED ISSUE #1191: [query] pretty print for the client border line
**Summary**

The text broken the MySQL border line:
```
mysql> explain select max(number) from numbers(1000) group by number%3;
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| explain                                                                                                                                                                                                                                                                                                                                                                  |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection: max(number):UInt64
  AggregatorFinal: groupBy=[[(number % 3)]], aggr=[[max(number)]]
    AggregatorPartial: groupBy=[[(number % 3)]], aggr=[[max(number)]]
      Expression: (number % 3):UInt8, number:UInt64 (Before GroupBy)
        ReadDataSource: scan partitions: [16], scan schema: [number:UInt64], statistics: [read_rows: 1000, read_bytes: 8000] |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

```

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

Summary about this PR

Regard the explain result of a plan to multiple rows rather than a single row so that we can have the complete borderline when the mysql client outputs `EXPLAIN` results.

Before the PR:
```
mysql> explain select max(number) from numbers(1000) group by number%3;
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| explain                                                                                                                                                                                                                                                                                                                                                                  |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection: max(number):UInt64
  AggregatorFinal: groupBy=[[(number % 3)]], aggr=[[max(number)]]
    AggregatorPartial: groupBy=[[(number % 3)]], aggr=[[max(number)]]
      Expression: (number % 3):UInt8, number:UInt64 (Before GroupBy)
        ReadDataSource: scan partitions: [16], scan schema: [number:UInt64], statistics: [read_rows: 1000, read_bytes: 8000] |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

After the PR:
```
mysql> explain select max(number) from numbers(1000) group by number%3;
+-----------------------------------------------------------------------------------------------------------------------------+
| explain                                                                                                                     |
+-----------------------------------------------------------------------------------------------------------------------------+
| Projection: max(number):UInt64                                                                                              |
|   AggregatorFinal: groupBy=[[(number % 3)]], aggr=[[max(number)]]                                                           |
|     AggregatorPartial: groupBy=[[(number % 3)]], aggr=[[max(number)]]                                                       |
|       Expression: (number % 3):UInt8, number:UInt64 (Before GroupBy)                                                        |
|         ReadDataSource: scan partitions: [8], scan schema: [number:UInt64], statistics: [read_rows: 1000, read_bytes: 8000] |
+-----------------------------------------------------------------------------------------------------------------------------+
5 rows in set (0.01 sec)
```

## Changelog

- Bug Fix
- Improvement

## Related Issues

Fixes #1191

## Test Plan

Unit Tests

### CODE REVIEW

**Comment by xuyifangreeneyes** [comment]
@BohuTANG @sundy-li @zhang2014 PTAL

**Comment by BohuTANG** [comment]
@xuyifangreeneyes 
Great, would like to know how you locate this problem?
BTW, make lint will make the cargo lint happy.

**Comment by zhang2014** [comment]
What happen in clickhouse-client?

**Comment by BohuTANG** [comment]
> What happen in clickhouse-client?

Same issue for both MySQL and ClickHouse client

**Comment by xuyifangreeneyes** [comment]
> @xuyifangreeneyes
> Great, would like to know how you address this problem?
> BTW, make lint will make the cargo lint happy.
> And, make test will run the tests locally.

Before the PR, the plan tree, i.e., the explain result is a single-row-single-column cell. Since the string of the plan tree contains `\n`, several rows are printed at the client but the borderline is missing. I treat the plan tree as multiple-row-single-column cells, which makes the borderline work fine.

I have a question about the test. I run `make test` on master branch on mac os and some testcases fail.
```
<img width="1430" alt="Screen Shot 2021-08-03 at 11 19 40 AM" src="https://user-images.githubusercontent.com/30385241/128602329-e44e8cce-06a8-4529-be7a-e1ef5f5740b9.png">

**Comment by sundy-li** [comment]
That's ok, the failed unit tests are not related to your change.

And: 
- Take a look at the failed stateless tests.
-  ClickHouse client behavior after these changes.

**Comment by BohuTANG** [comment]
> > @xuyifangreeneyes
> > Great, would like to know how you address this problem?
> > BTW, make lint will make the cargo lint happy.
> > And, make test will run the tests locally.
> 
> Before the PR, the plan tree, i.e., the explain result is a single-row-single-column cell. Since the string of the plan tree contains `\n`, several rows are printed at the client but the borderline is missing. I treat the plan tree as multiple-row-single-column cells, which makes the borderline work fine.
> 
> I have a question about the test. I run `make test` on master branch on mac os and some testcases fail.
> Screen Shot 2021-08-07 at 9 47 12 PM

Hi！
For the flasky test, @dantengsky may give some help here.
As sundy suggested, the stateless test results need some improvement after this PR(mainly explain tests).

**Comment by xuyifangreeneyes** [comment]
ClickHouse client behavior

Before the PR:
```
datafuse :) explain select max(number) from numbers(1000) group by number%3;

EXPLAIN
SELECT max(number)
FROM numbers(1000)
GROUP BY number % 3

Query id: 34fb147d-b73c-4a8f-8ef9-b19ddd482c19

Connecting to 0.0.0.0:9001 as user default.
Connected to datafuse server version 2021.5.0 revision 54405.

ClickHouse client version is older than ClickHouse server. It may lack support for new features.

┌─explain────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Projection: max(number):UInt64
  AggregatorFinal: groupBy=[[(number % 3)]], aggr=[[max(number)]]
    AggregatorPartial: groupBy=[[(number % 3)]], aggr=[[max(number)]]
      Expression: (number % 3):UInt8, number:UInt64 (Before GroupBy)
        ReadDataSource: scan partitions: [8], scan schema: [number:UInt64], statistics: [read_rows: 1000, read_bytes: 8000] │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.204 sec.
```

After the PR:
```
datafuse :) explain select max(number) from numbers(1000) group by number%3;

EXPLAIN
SELECT max(number)
FROM numbers(1000)
GROUP BY number % 3

Query id: a223c140-d155-48e0-ac8b-b4d65afbc6ba

Connecting to 0.0.0.0:9001 as user default.
Connected to datafuse server version 2021.5.0 revision 54405.

ClickHouse client version is older than ClickHouse server. It may lack support for new features.

┌─explain─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Projection: max(number):UInt64                                                                                              │
│   AggregatorFinal: groupBy=[[(number % 3)]], aggr=[[max(number)]]                                                           │
│     AggregatorPartial: groupBy=[[(number % 3)]], aggr=[[max(number)]]                                                       │
│       Expression: (number % 3):UInt8, number:UInt64 (Before GroupBy)                                                        │
│         ReadDataSource: scan partitions: [8], scan schema: [number:UInt64], statistics: [read_rows: 1000, read_bytes: 8000] │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

5 rows in set. Elapsed: 0.060 sec.
```

**Review by BohuTANG — APPROVED** [review]
LGTM
Thank you @xuyifangreeneyes

**Pull request merged**
