### PR TITLE
support substring function with minus argument

### LINKED ISSUE #573: SUBSTRING: Unsupported expression: - 3
**Describe the bug**
```
mysql> SELECT SUBSTRING('1234567890' FROM -3 FOR 3);
ERROR 1105 (HY000): Code: 5, displayText = Unsupported expression: - 3, type: UnaryOp { op: Minus, expr: Value(Number("3", false)) }.
```

expect:
```
+--------------------------------+
| SUBSTRING('1234567890', -3, 3) |
+--------------------------------+
| 890                            |
+--------------------------------+
```

### PR DESCRIPTION
**Pull request by b41sh**
## Summary

support substring function with minus argument

## Changelog

- Improvement

## Related Issues

Fixes #573

## Test Plan

Unit Tests
Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
Thanks for the contribution, I will take look at it after #550

**Review by BohuTANG — APPROVED** [review]
LGTM
Thank you @b41sh 
Let's merge

**Comment by sundy-li** [comment]
@b41sh  seems we need a stateless test like  https://github.com/datafuselabs/datafuse/blob/master/tests/suites/0_stateless/00_0000_dummy_select_1.sql .

I test the unit test, it works. But it did not work in mysql-client;
```
mysql>  select substring('1234567890',-3,3);
ERROR 1105 (HY000): Code: 1002, displayText = sql parser error: Expected ), found: ,.
mysql>
```


Could you create another pr to improve it?

**Comment by b41sh** [comment]
> @b41sh seems we need a stateless test like https://github.com/datafuselabs/datafuse/blob/master/tests/suites/0_stateless/00_0000_dummy_select_1.sql .
> 
> I test the unit test, it works. But it did not work in mysql-client;
> 
> ```
> mysql>  select substring('1234567890',-3,3);
> ERROR 1105 (HY000): Code: 1002, displayText = sql parser error: Expected ), found: ,.
> mysql>
> ```
> 
> Could you create another pr to improve it?

@sundy-li this PR implements the following SQL, I will add some test cases for it.
```
SELECT SUBSTRING('1234567890' FROM -3 FOR 3);
```

`select substring('1234567890',-3,3);` has different grammar, we need to modify parser. I can implement it in another PR.

**Comment by BohuTANG** [comment]
Related to #615

**Pull request merged**
