### PR TITLE
Introduce plan visitor to refine optimizer

### PR DESCRIPTION
**Pull request by leiysky**
## Summary

This PR introduce a `PlanVisitor` that implements visitor pattern, which reference a rust-idiomatic visitor [syn](https://docs.rs/syn/1.0.72/syn/visit/index.html).

The motivation I file this PR is to provide a better way to implement optimizer. When I was trying to write some heuristic optimization rules, I found it's inconvenient to maintain state and partially delegate the logic of traversal to default implementation with current framework.

In this PR I provide a `PlanVisitor` trait and refactor the `ProjectionPushDown` optimization with visitor pattern which has passed regression unit test.

## Changelog

- Improvement

## Test Plan

Unit Tests
Stateless Tests

### CODE REVIEW

**Comment by leiysky** [comment]
By the way, I removed return value of `set_input` since it seems doesn't make sense. IMO, it's better to just panic if there is any issue with such simple action.

**Comment by BohuTANG** [comment]
This would be a neat feature for planner, thank you @leiysky 
We will review it carefully next.

**Comment by BohuTANG** [comment]
Oops, github action is Incident
https://www.githubstatus.com/incidents/zbpwygxwb3gw

**Comment by leiysky** [comment]
> Oops, github action is Incident
> https://www.githubstatus.com/incidents/zbpwygxwb3gw

Seems Github crashed again... How to rerun the actions?

**Comment by BohuTANG** [comment]
> > Oops, github action is Incident
> > https://www.githubstatus.com/incidents/zbpwygxwb3gw
> 
> Seems Github crashed again... How to rerun the actions?

Have re-run the jobs manually.
BTW, we can re-run it from the job page(click `details`), for example:
https://github.com/datafuselabs/datafuse/pull/557/checks?check_run_id=2594064640

**Comment by BohuTANG** [comment]
@leiysky  
Looks great to me.
Can we using the visitor partern replace the `plan_walker.rs`? But not sure how to handle the pre-order/post-order.

**Comment by leiysky** [comment]
> @leiysky
> Looks great to me.
> Can we using the visitor partern replace the `plan_walker.rs`? But not sure how to handle the pre-order/post-order.

Generally, you can customize traversal order. For example:
```rust
struct PreOrder {
    pub process: FnMut(&PlanNode)
}

impl<'plan> PlanVisitor<'plan> for PreOrder {
    fn visit_plan_node(&mut self, plan: &PlanNode) {
        self.process(plan);
        PlanVisitor::visit_plan_node(self, plan.input().as_ref());
    }
}

struct PostOrder {
    pub process: FnMut(&PlanNode)
}

impl<'plan> PlanVisitor<'plan> for PostOrder {
    fn visit_plan_node(&mut self, plan: &PlanNode) {
        PlanVisitor::visit_plan_node(self, plan.input().as_ref());
        self.process(plan);
    }
}
```

I'll add this part to rustdoc.

**Comment by leiysky** [comment]
@BohuTANG I just refactored `walk_preorder` and `walk_postorder` with `PlanVisitor` so we can keep them.

**Review by BohuTANG — APPROVED** [review]
LGTM
Thank you @leiysky

**Pull request merged**
