### PR TITLE
Tracking: Catalog (issue #867)

### LINKED ISSUE #835: Database catalog should shared to multiple sessions
**Summary**
Database catalog should shared to multiple sessions

- [x] MySQL Handler [#704]
- [x] ClickHouse Handler [#931 ]

https://github.com/datafuselabs/datafuse/blob/064820f75faa3e4ba658377ef1910a9f1d2a0d8c/fusequery/query/src/sessions/context.rs#L46-L64

### LINKED ISSUE #867: Catalog API
**Summary**

Currently `DataSource` API provides us the essential functionalities of manipulating metadata,  but as we moving the v0.5,  some extra requirements should be fulfilled, including but not limited to:

  - <del>periodically sync metadata with(from) meta-store</del>
  - metadata of database, table should be versioned, as we are going to provide time travel features
  - exposes a session-level catalog API so that we can keep uncommitted metadata invisible
  - provide simple transaction API
    for per statement, implicit transaction. 
    Note: In v0.5 we are not going to support distributed/parallel insertion/deletion

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

TBD

## Changelog

- New Feature

## Related Issues

Fixes #835
Fixes #867

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Hi @dantengsky 

Little tips here:
The  Changelog in the PR template just for categorisation and auto labeled by datafuse-bot, we don't need TDB, just need to select one or more categories:
- New Feature
- Bug Fix
- Improvement
- Performance Improvement
- Build/Testing/CI
- Documentation
- Website
- Other 
- Not for changelog (changelog entry is not required)

We can see the categories are used in:
https://github.com/datafuselabs/datafuse/releases

**Comment by dantengsky** [comment]
got it and thanks!

**Comment by BohuTANG** [comment]
I have changed and auto labeled by datafuse-bot :dancers:

**Comment by dantengsky** [comment]
As sub-tasks are all merged into master :

 -  #1169
 -  #1176
 - #1212 

There will be no significant refactoring before v0.5(except #1286). 

I am closing this issue. 


P.S. Refactoring of Catalog API in the next stage should be taken into account with refactoring of other components, especially 
 #1219

**Pull request closed without merging**
