### PR TITLE
[commons] arrow -> arrow2

### LINKED ISSUE #1170: Considering migrate to arrow2
**Summary**

From Reddit: https://www.reddit.com/r/rust/comments/ooyhn1/release_of_arrow2_01_and_parquet2_01/

Features depends on arrow2, to be filled

- [x]  jorgecarleitao/arrow2#215
- [ ] https://github.com/jorgecarleitao/arrow2/issues/245

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

Summary about this PR

## Changelog

- Improvement

## Related Issues

Fixes #1170 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
Baseline benchmarks compare arrow1 vs arrow2 shows greate performance improvement.

https://github.com/sundy-li/learn/tree/master/arrow-vs-arrow2/benches

```
argo bench -- "arrow2-min 2\^13 f32"
arrow2-min 2^13 f32     time:   [1.5618 us 1.5680 us 1.5752 us]

argo bench -- "arrow1-min 2\^13 f32"
arrow1-min 2^13 f32     time:   [3.1624 us 3.1732 us 3.1855 us]

```

After migrated datafuse into arrow2, the performance shows not much difference.

[perf-results](https://github.com/sundy-li/learn/blob/master/arrow-vs-arrow2/perf-arrow2-datafuse.html)

Arrow2 makes the code be much more clear and simple, so it's still better to have it.

**Comment by BohuTANG** [comment]
Performance with my AMD Ryzen 7 PRO 4750U(Still faster in most cases, expect for last two case):

| Query                                                        | arrow1(master)                                 | arrow2                                         |
| ------------------------------------------------------------ | --------------------------------------------------- | ------------------------------------------------------------ |
| SELECT avg(number) FROM numbers_mt(100000000000)             | 4.35 s.<br /> (22.97 billion rows/s., 183.91 GB/s.) |  4.17 s. <br /> (23.98 billion rows/s., 191.84 GB/s.) |
| SELECT sum(number) FROM numbers_mt(100000000000)             | 4.20 s.<br />(23.79 billion rows/s., 190.50 GB/s.)  |  3.72 s. <br />(26.82 billion rows/s., 214.59 GB/s.) |
| SELECT min(number) FROM numbers_mt(100000000000)             | 4.92 s.<br />(20.31 billion rows/s., 162.64 GB/s.)  |   4.3 s. <br /> (22.90 billion rows/s., 183.17 GB/s.) |
| SELECT max(number) FROM numbers_mt(100000000000)             | 4.77 s.<br />(20.95 billion rows/s., 167.78 GB/s.)  |   4.3 s. <br /> (22.90 billion rows/s., 183.17 GB/s.) |
| SELECT count(number) FROM numbers_mt(100000000000)           | 2.91 s.<br />(34.33 billion rows/s., 274.90 GB/s.)  |  2.31 s <br /> (43.21 billion rows/s., 345.66 GB/s.) |
| SELECT sum(number+number+number) FROM numbers_mt(100000000000) | 19.83 s.<br />(5.04 billion rows/s., 40.37 GB/s.)   | 16.16 s <br /> (6.19 billion rows/s., 49.50 GB/s.)|
| SELECT sum(number) / count(number) FROM numbers_mt(100000000000) | 3.90 s.<br />(25.62 billion rows/s., 205.13 GB/s.)  | 3.91 s <br /> (25.57 billion rows/s., 204.57 GB/s.) |
| SELECT sum(number) / count(number), max(number), min(number) FROM numbers_mt(100000000000) | 8.28 s.<br />(12.07 billion rows/s., 96.66 GB/s.)   | 8.21 S <br />  (12.17 billion rows/s., 97.34 GB/s.) |
| SELECT number FROM numbers_mt(10000000000) ORDER BY number DESC LIMIT 100 | 4.80 s.<br />(2.08 billion rows/s., 16.67 GB/s.)    | 5.37 s <br /> (1.86 billion rows/s., 14.88 GB/s.) |
| SELECT max(number), sum(number) FROM numbers_mt(1000000000) GROUP BY number % 3, number % 4, number % 5 | 6.31 s.<br />(158.49 million rows/s., 1.27 GB/s.) | 7.0 s <br /> (141.51 million rows/s., 1.13 GB/s.) |


cc @sundy-li @zhang2014

**Comment by sundy-li** [comment]
Ok, but the baseline of sort performance is poor, I'm trying to find the bottleneck in arrow2.

https://github.com/jorgecarleitao/arrow2/issues/245

**Comment by BohuTANG** [comment]
> Ok, but the baseline of sort performance is poor, I'm trying to find the bottleneck in arrow2.
> 
> [jorgecarleitao/arrow2#245](https://github.com/jorgecarleitao/arrow2/issues/245)

I have seen it, if it solved, arrow2 all is top performance against arrow1

**Comment by BohuTANG** [comment]
For the groupby, may be the first test is fast in that time, i think we can meaused that again when the sort sloved.

**Review by BohuTANG — APPROVED** [review]
LGTM

**Comment by jorgecarleitao** [comment]
I believe that the group by perf can be addressed with the `arrow2::compute::hash` kernel: hash the arrays one by one and merge the hashes

**Comment by sundy-li** [comment]
> arrow2::compute::hash

The current design in datafuse is `non-conflict compact hash combination`.

1. Group by String,  the combination key is binary as `Vec<u8>`
2. Group by UInt32, the combination key is UInt32
3. Group by UInt8, UInt8, UInt8,  the combination key is UInt32, left last 8bytes zeroed.

**Pull request merged**
