### PR TITLE
[common/arrow] add simd feature

### PR DESCRIPTION
**Pull request by PsiACE**
Signed-off-by: Chojan Shang <psiace@outlook.com>

I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

Just add simd feature for common-arrow to provide a way to enable `arrow/simd` support.

## Changelog

- Build/Testing/CI

## Related Issues

Related #329 #750

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
@PsiACE 
Looks great, thanks.
What happens if the machine doesn't support SIMD?

**Comment by PsiACE** [comment]
> @PsiACE
> Looks great, thanks.
> What happens if the machine doesn't support SIMD?

Currently no impact, this feature is not enabled by default. 

Ideally, we should detect the target platform.

**Comment by BohuTANG** [comment]
> > @PsiACE
> > Looks great, thanks.
> > What happens if the machine doesn't support SIMD?
> 
> Currently no impact, this feature is not enabled by default.
> 
> Ideally, we should detect the target platform.

Arrow has the platform detect, but always not work.

**Review by BohuTANG — APPROVED** [review]
LGTM

**Pull request merged**
